import { GraphQLObjectType, GraphQLString, GraphQLFloat } from 'graphql';

export const ClinicType = new GraphQLObjectType({
  name: 'Clinic',
  fields: {
    longNameVersion:{ type: GraphQLString },
    typeformRegistrationLink: { type: GraphQLString },
    pms: { type: GraphQLString },
    metaTitle: { type: GraphQLString },
    metaDescription: { type: GraphQLString },
    slug: { type: GraphQLString },
    website: { type: GraphQLString },
    clinicName: { type: GraphQLString },
    displayOnWeb: { type: GraphQLString },
    linkToClinicSuburbPage: { type: GraphQLString },
    fullAddress: { type: GraphQLString },
    city: { type: GraphQLString },
    suburb: { type: GraphQLString },
    state: { type: GraphQLString },
    postcode: { type: GraphQLString },
    email: { type: GraphQLString },
    phone: { type: GraphQLString },
    nearby1Txt: { type: GraphQLString },
    nearby1Link: { type: GraphQLString },
    nearby2Txt: { type: GraphQLString },
    nearby2Link: { type: GraphQLString },
    nearby3Txt: { type: GraphQLString },
    nearby3Link: { type: GraphQLString },
    nearby4Txt: { type: GraphQLString },
    nearby4Link: { type: GraphQLString },
    aboutClinic: { type: GraphQLString },
    latitude: { type: GraphQLFloat },
    longitude: { type: GraphQLFloat }
  },
});

export const CityType = new GraphQLObjectType({
  name: 'City',
  fields: {
    citySlug: { type: GraphQLString },
    cityName: { type: GraphQLString },
    state: { type: GraphQLString },
    metaTitle: { type: GraphQLString },
    metaDescription: { type: GraphQLString },
    h1: { type: GraphQLString },
    h2: { type: GraphQLString },
    subHeadingText: { type: GraphQLString },
    tick1: { type: GraphQLString },
    tick2: { type: GraphQLString },
    tick3: { type: GraphQLString },
    aboutBookphysio: { type: GraphQLString },
    latitude: { type: GraphQLFloat },
    longitude: { type: GraphQLFloat }
  },
});

export const SuburbType = new GraphQLObjectType({
  name: 'Suburb',
  fields: {
    suburbSlug: { type: GraphQLString },
    suburbName: { type: GraphQLString },
    city: { type: GraphQLString },
    state: { type: GraphQLString },
    postcode: { type: GraphQLString },
    metaTitle: { type: GraphQLString },
    metaDescription: { type: GraphQLString },
    h1: { type: GraphQLString },
    h2: { type: GraphQLString },
    aboutBookphysio: { type: GraphQLString },
    nearby1Link: { type: GraphQLString },
    nearby1Txt: { type: GraphQLString },
    nearby1State: { type: GraphQLString },
    nearby1Postcode: { type: GraphQLString },
    nearby2Link: { type: GraphQLString },
    nearby2Txt: { type: GraphQLString },
    nearby2State: { type: GraphQLString },
    nearby2Postcode: { type: GraphQLString },
    nearby3Link: { type: GraphQLString },
    nearby3Txt: { type: GraphQLString },
    nearby3State: { type: GraphQLString },
    nearby3Postcode: { type: GraphQLString },
    nearby4Link: { type: GraphQLString },
    nearby4Txt: { type: GraphQLString },
    nearby4State: { type: GraphQLString },
    nearby4Postcode: { type: GraphQLString },
    latitude: { type: GraphQLFloat },
    longitude: { type: GraphQLFloat }
  },
});
